package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFF15162)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdadb)
val md_theme_light_onPrimaryContainer = Color(0xFF41000a)
val md_theme_light_secondary = Color(0xFF08C8AD)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF62fadd)
val md_theme_light_onSecondaryContainer = Color(0xFF00201a)
val md_theme_light_tertiary = Color(0xFF5B3B97)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFecdcff)
val md_theme_light_onTertiaryContainer = Color(0xFF25005a)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF9C9C9C)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFffb3b7)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb3b7)
val md_theme_dark_onPrimary = Color(0xFF680016)
val md_theme_dark_primaryContainer = Color(0xFF920025)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdadb)
val md_theme_dark_secondary = Color(0xFF3bddc1)
val md_theme_dark_onSecondary = Color(0xFF00382e)
val md_theme_dark_secondaryContainer = Color(0xFF005144)
val md_theme_dark_onSecondaryContainer = Color(0xFF62fadd)
val md_theme_dark_tertiary = Color(0xFFd4baff)
val md_theme_dark_onTertiary = Color(0xFF3c1977)
val md_theme_dark_tertiaryContainer = Color(0xFF54338f)
val md_theme_dark_onTertiaryContainer = Color(0xFFecdcff)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFFb4233a)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)

//Customn color values
val md_theme_white = Color(0xFFFFFFFF)
val md_theme_text_primary = Color(0xFF141817)
val md_theme_text_secondary = Color(0xC4141817)
val md_theme_text_tertiary = Color(0x9C141817)
val md_theme_text_hint = Color(0xFF7d8180)
val md_theme_text_green = Color(0xFF00bfa5)
val md_theme_text_orange = Color(0xFFFF9D57)
val md_theme_text_red = Color(0xFFF03F54)
val md_theme_stroke = Color(0xa6020818)
val md_theme_divider = md_theme_light_onSurfaceVariant
val md_theme_sleep_card_color = Color(0xFF605CB8)

val md_theme_awake_sleep_color = Color(0xFF38ADA9)
val md_theme_rem_sleep_color = Color(0xFF3C6382)
val md_theme_deep_sleep_color = Color(0xFF1E3799)
val md_theme_light_sleep_color = Color(0xFF6A89CC)